services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./db_data:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3307
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  # nodeapp:
  #   container_name: nodeappcontainer
  #   image: nodeapp:v1
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/usr/code
  #   ports:
  #     - 3000:3000
  #   expose:
  #     - 3000
  #   environment:
  #     DB_HOST: mysqldb
  #     DB_PORT: 3307
  #     DB_USER: "admin"
  #     DB_PASSWORD: "root"
  #     DB_NAME: usersdb
  #     DB_CONNECTION_LIMIT: 10
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: nodeappservice
  #     SERVER_PORT: 3000
  #   depends_on:
  #     - mysqldb
  #   networks:
  #     - internalnet

networks:
  internalnet:
    driver: bridge
#
#
# > docker exec -it mysqlcontainer /bin/bash
# root@4a8fe8b51552:/# mysql -u root -p
# Enter password:

# docker-compose up -d --build
